# Generated by Django 3.2.16 on 2022-12-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photographers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('best_photo', models.CharField(max_length=120)),
                ('photo_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
